apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/ddevadat/argo-vault-plugin-demo'
    targetRevision: HEAD
    path: deployments/nginx/manifests
    plugin:
      name: argocd-vault
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: true
      selfHeal: true