apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: false
      selfHeal: false
  source:
    repoURL: 'https://github.com/ddevadat/argo-vault-plugin-demo'
    targetRevision: HEAD
    path: argocd/apps/nginx

    # We're telling Argo CD to use our plugin to deploy the manifests
    plugin:
      name: argocd-vault
